description: "This research project develops training materials for reseachers wanting to learn to build project
websites in GitHub with GitHub Pages."
email: "ataylor@poly.ac.mw"
twitterurl:"poly_ai_cit"
